name: front_mobile
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  carousel_slider: ^4.1.1
  http: ^0.13.5
  api_cache_manager: ^1.0.2
  sqflite: ^2.0.3+1
  get_storage: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^1.1.6
  cached_network_image: ^3.0.0
  dio: ^5.1.2
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  

  uses-material-design: true

  
  assets:
    - assets/images/
    - .env

 
  # example:
  fonts:
    - family: SignikaNegative
      fonts:
        - asset: assets/fonts/SignikaNegative-VariableFont_wght.ttf
    
