import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'uz_UZ': {
          'Home': 'Bosh sahifa',
          'search': 'Qidiruv',
          'cart': 'Savatcha',
          'Desire': 'Sevimli',
          'cobinet': 'Kobinet',
          '_lang': 'Ilova tili',
          'My_orders': 'Buyurtmalarim',
          'My_comments': 'Sharxlarim',
          'My_promo_codes': 'Promokodlarim',
          'Notifications': 'Bildirishnomalar',
          'Settings': 'Sozlamalar',
          'City': 'Shahar',
          'Delivery_points_on_the_map': 'Xaritadagi topshirish punkitlari',
          'Information': 'Ma\'lumot',
          'contact_us': 'Biz bilan bog\'lanish',
          'Log_out_of_profile': 'Biz bilan bog\'lanish',
          'Version': 'Versiya',
          'My_chats': 'Chatlarim',
          'my_profile': 'Profilim',
        },
        'ru_RU': {
          'Home': 'Главная',
          'search': 'Поиск',
          'cart': 'Корзина',
          'Desire': 'Желание',
          'cobinet': 'Кабинет',
          '_lang': 'Язык приложения',
          'My_orders': 'Мои заказы',
          'My_comments': 'Мои комментарии',
          'My_promo_codes': 'Мои промокоды',
          'Notifications': 'Уведомления',
          'Settings': 'Настройки',
          'City': 'Город',
          'Delivery_points_on_the_map': 'Точки доставки на карте',
          'Information': 'Информация',
          'contact_us': 'Cвяжитесь с нами',
          'Log_out_of_profile': 'Выйти из профиля',
          'Version': 'Версия',
          'My_chats': 'Мои чаты',
          'my_profile': 'Мой профиль',
        },
        'en_US': {
          'Home': 'Home',
          'search': 'Search',
          'cart': 'Cart',
          'Desire': 'Desire',
          'cobinet': 'Cabinet',
          '_lang': 'Application language',
          'My_orders': 'My orders',
          'My_comments': 'My comments',
          'My_promo_codes': 'My promo codes',
          'Notifications': 'Notifications',
          'Settings': 'Settings',
          'City': 'City',
          'Delivery_points_on_the_map': 'Delivery points on the map',
          'Information': 'Information',
          'contact_us': 'Contact us',
          'Log_out_of_profile': 'Log out of profile',
          'Version': 'Version',
          'My_chats': 'My chats',
          'my_profile': 'My profile',
        },
      };
}
