import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'uz_UZ': {
          'new_group': 'Yangi guruh',
          '_lang': 'Til',
          '_contacts': 'Kontaktlar',
          'map_users': 'Yaqin atrofdagi odamlar',
          '_settings': 'Sozlamalar',
          'like_to_add': "Kimni qo'shishni xoxlaysiz?",
          'click_to_edit_the_phone_number': "Telefon raqamini tahrirlash uchun bosing",
          'username': "Foydalanuvchi nomi",
          'biography': "Tarjimai hol",
          'edit_name': "Ismni tahrirlash",
          'log_out': "Chiqish",
          'edit_profile_image': "Profil rasmini tahrirlash",
          'enter_your_first_name': "Ism familyangizni kiriting",
          'name': "Ism",
          'surname': "Familya",
          'profile_pictures': "Profil rasmlari",
          'edit_profile_pictures': "Profil rasmini tahrirlash",
          'gallery': "Galareya",
          'camera': "Kamera",
          'chats': "Chatlar",
          'groups': "Guruhlar",
          'posts': "Postlar",
          'notifications': "Bildirishnomalar",
          'new_message': "Yangi xabar",
          'sort_by_last_activity': "Oxirgi faollik bo'yicha tartiblash",
          'search': "Qidiruv",
          'was_online_recently': "Yaqinda online edi",
          'message': "Xabar",
          'picture': "Rasm",
          'file': "Fayl",
          'location': "Joylashuv",
          'attention': "Diqqat",
          'confirmation': "Tasdiqlash",
          'cancel': "Bekor qilish",
          'confirm_deletion': "O'chirishni tasdiqlaysizmi?",
          'pictures': "Rasmlar",
          'videos': "Videolar",
          'audios': "Audiolar",
          'all': "Barchasi",
          'upload_a_picture': "Rasmni yuklash",
          'file_downloaded': "Fayl yuklab olindi",
          'phone_number': "Telefon raqam",
          'edit_phone_number': "Telefon raqamni tahrirlash",
          'enter_the_code_sent_to_the_number_below': "Quydagi raqamga yuborilgan kodni kiriting",
          'time_to_send_a_new_SMS_code': "Yangi SMS-kod yuborish vaqti:",
          'resend': "Qayta yuborish",
          'edit_username_info_text': "Chatda foydalanuvchi nomini tanlashingiz mumkin. Agar shunday qilsangiz, odamlar sizni ushbu foydalanuvchi nomi bilan topish va telefon raqamingiz zarur bo'lmagan holda siz bilan bog'lanishi mumkin.",
          'edit_username_info_text_two': "a-z, 0-9 va _ belgilaridan foydalanishingiz mumkin. Minimal uzunlik - 5ta belgi",
          'about_you': "O'zingiz haqingizda bir necha satrlar qo'shishingiz mumkin. Profil ochadigan har bir kishi bu matnni ko'radi",
          'turn_on_GPS_service_from_your_phone': "Telefoningizdan GPS hizmati yoqing",
          'delete_and_leave_the_group': "O'chirish va guruhni tark etish",
          'delete': "O'chirish",
          'do_you_want_to_leave_the_group': "Guruhdan chiqmoqchimisiz?",
          'add_members': "A'zolar qo'shish",
          'members': "A'zolar",
          'loading_file': "Fayl yuklanmoqda",
          'post_a_group_photo': "Guruh rasmini qo'yish",
          'do_you_want_to_delete_the_group': "Guruhni o'chirmoqchimisiz?",
          'admins': "Adminlar",
          'personal': "Shaxsiy",
          'public': "Ommaviy",
          'group_name': "Guruh nomi",
          'assign_a_new_image': "Yangi rasm belgilash",
          'group_type': "Guruh turi",
          'editing': "Tahrirlash",
          'what_news_do_you_have': "Sizda nima yangiliklar?",
          'create_a_post': "Post yaratish",
          'visited_your_profile': "sizni profilingizni kuzatdi",
          'liked_the_post_you_posted': "siz joylagan post yoqdi",
          'commented_on_the_post_you_posted': "siz joylagan postga izox qoldirdi",
          'responded_to_your_comment_in_the_post': "postda yozgan izoxingizga javob qaytardi",
          'are_you_sure_you_want_to_blacklist_this_user': "Rostan ushbu foydalanuvchini qora ro'yhatga solmoqchimisiz?",
          'Privacy_and_Security': "Maxfiylik va xafsizlik",
          'Account': "Hisob",
          'Blocked_users': "Bloklangan foydalanuvchilar",
          'Safety': "Xavfsizlik",
          'count_blocked_users': "ta bloklangan foydalanuvchi",
          'unblok_a_user': "Foydalanuvchini blockdan chiqarasizmi?",
          'There_are_no_blocked_users': "Bloklangan foydalanuvchilar mavjud emas",
          'Chats_are_not_available': "Chatlar mavjud emas",
          'Devices': "Qurulmalar",
          'Confidentiality': "Maxfiylik",
          'Start_a_new_chat': "Yangi chat boshlash",
          'Turn_on_the_GPS_service_from_your_phone': "Telefoningizdan GPS xizmatini yoqing",
          'show_phone_all': "Hamma",
          'show_phone_not_all': "Hech kim",
          'Who_can_see_my_phone_number': "Telefon raqamimni kimlar ko'rishi mumkin?",
          'Private_group': "Shaxsiy guruh",
          'Mass_group_text': "Ommaviy guruhlar qidiruv orqali topilish imkoniyatiga ega va har kim unga qo'shilishi mumkin",
          'phone_number_all_text': "Profilingizga tashrif buyurganlar telefon raqamingizni ko'ra olishadi",
          'phone_number_not_all_text': "Telefon raqamingizni hech kim ko'ra olmaydi",
        },
        'ru_Ru': {
          'new_group': 'Новая группа',
          '_lang': 'Язык',
          '_contacts': 'Контакты',
          'map_users': 'Люди поблизости',
          '_settings': 'Настройки',
          'like_to_add': 'Кого бы вы хотели добавить?',
          'click_to_edit_the_phone_number': 'Нажмите, чтобы изменить номер телефона',
          'username': 'Имя пользователя',
          'biography': 'Биография',
          'edit_name': 'Редактировать имя',
          'log_out': 'Выход',
          'edit_profile_image': 'Изменить изображение профиля',
          'enter_your_first_name': 'Введите свое имя',
          'name': 'Имя',
          'surname': 'фамилия',
          'profile_pictures': 'Изображение профиля',
          'edit_profile_pictures': 'Редактировать изображения профиля',
          'gallery': 'Галерея',
          'camera': 'Камера',
          'chats': 'Чаты',
          'groups': 'Группы',
          'posts': 'Новости',
          'notifications': 'Уведомления',
          'new_message': 'Новое сообщение',
          'sort_by_last_activity': 'Сортировать по последнему действию',
          'search': 'Поиск',
          'was_online_recently': 'недавно был в сети',
          'message': 'Сообщение',
          'picture': "Рисунок",
          'file': "Файл",
          'location': "Место нахождения",
          'attention': "Внимание",
          'confirmation': "Подтверждение",
          'cancel': "Отмена",
          'confirm_deletion': "Подтвердить удаление?",
          'pictures': "Фотографий",
          'videos': "Ролики",
          'audios': "Аудио",
          'all': "Все",
          'upload_a_picture': "Загрузить изображение",
          'file_downloaded': "Файл загружен",
          'phone_number': "Номер телефона",
          'edit_phone_number': "Изменить номер телефона",
          'enter_the_code_sent_to_the_number_below': "Введите код, отправленный на номер ниже",
          'time_to_send_a_new_SMS_code': "Время отправить новый SMS-код:",
          'resend': "Отправить",
          'edit_username_info_text': "Вы можете выбрать имя пользователя в чате. Если вы сделаете это, люди смогут найти вас с этим именем пользователя и связаться с вами, не нуждаясь в вашем номере телефона.",
          'edit_username_info_text_two': "Вы можете использовать az, 0-9 и _. Минимальная длина - 5 символов",
          'about_you': "Можно добавить несколько строк о себе. Любой, кто откроет профиль, увидит этот текст",
          'turn_on_GPS_service_from_your_phone': "Включите службу GPS на своем телефоне",
          'delete_and_leave_the_group': "Удалить и покинуть группу",
          'delete': "Удалить",
          'do_you_want_to_leave_the_group': "Вы хотите выйти из группы?",
          'add_members': "Добавить участников",
          'members': "Участники",
          'loading_file': "Загрузка файла",
          'post_a_group_photo': "Опубликовать групповое фото",
          'do_you_want_to_delete_the_group': "Вы хотите удалить группу?",
          'admins': "Админы",
          'personal': "Личный",
          'public': "Общественный",
          'group_name': "Имя группы",
          'assign_a_new_image': "Назначить новое изображение",
          'group_type': "Тип группы",
          'editing': "Редактирование",
          'what_news_do_you_have': "Какие у вас новости?",
          'create_a_post': "Создать сообщение",
          'visited_your_profile': "посетил ваш профиль",
          'liked_the_post_you_posted': "понравился пост, который вы разместили",
          'commented_on_the_post_you_posted': "прокомментировал сообщение, которое вы разместили",
          'responded_to_your_comment_in_the_post': "ответил на ваш комментарий в посте",
          'are_you_sure_you_want_to_blacklist_this_user': "Вы уверены, что хотите добавить этого пользователя в черный список?",
          'Privacy_and_Security': "Конфиденциальность и безопасность",
          'Account': "Профиль",
          'Blocked_users': "Заблокированные пользователи",
          'Safety': "Безопасность",
          'count_blocked_users': "заблокированных пользователей",
          'unblok_a_user': "Разблокировать пользователь?",
          'There_are_no_blocked_users': "Нет заблокированных пользователей",
          'Chats_are_not_available': "Чаты недоступны",
          'Devices': "Устройства",
          'Confidentiality': "Конфиденциальность",
          'Start_a_new_chat': "Начать новый чат",
          'Turn_on_the_GPS_service_from_your_phone': "Включите службу GPS со своего телефона",
          'show_phone_all': "Все",
          'show_phone_not_all': "Никто",
          'Who_can_see_my_phone_number': "Кто может видеть мой номер телефона?",
          'Private_group': "Частная группа",
          'Mass_group_text': "Общедоступные группы доступны для поиска, и любой может присоединиться",
          'phone_number_all_text': "Посетители вашего профиля могут видеть ваш номер телефона",
          'phone_number_not_all_text': "Никто не может видеть ваш номер телефона",
        },
        'en_US': {
          'new_group': 'New group',
          '_lang': 'Language',
          '_contacts': 'Contacts',
          'map_users': 'People nearby',
          '_settings': 'Settings',
          'like_to_add': 'Who would you like to add?',
          'click_to_edit_the_phone_number': 'Click to edit the phone number',
          'username': 'Username',
          'biography': 'Biography',
          'edit_name': 'Edit name',
          'log_out': 'Log out',
          'edit_profile_image': 'Edit profile picture',
          'enter_your_first_name': 'Enter your first name',
          'name': 'Name',
          'surname': 'Surname',
          'profile_pictures': 'Profile pictures',
          'edit_profile_pictures': 'Edit profile pictures',
          'gallery': 'Gallery',
          'camera': 'Camera',
          'chats': 'Chats',
          'groups': 'Groups',
          'posts': 'Posts',
          'notifications': 'Notifications',
          'new_message': 'New message',
          'sort_by_last_activity': 'Sort by last activity',
          'search': 'Search',
          'was_online_recently': 'was online recently',
          'message': 'Message',
          'picture': "Picture",
          'file': "File",
          'location': "Location",
          'attention': "Attention",
          'confirmation': "Confirmation",
          'confirmation': "Confirmation",
          'cancel': "Cancel",
          'confirm_deletion': "Confirm deletion?",
          'pictures': "Pictures",
          'videos': "Vidoes",
          'audios': "Audios",
          'all': "All",
          'upload_a_picture': "Upload a picture",
          'file_downloaded': "File downloaded",
          'phone_number': "Phone number",
          'edit_phone_number': "Edit phone number",
          'enter_the_code_sent_to_the_number_below': "Enter the code sent to the number below",
          'time_to_send_a_new_SMS_code': "Time to send a new SMS code:",
          'resend': "Resend",
          'edit_username_info_text': "You can choose a username in the chat. If you do this, people will be able to find you with this username and contact you without needing your phone number",
          'edit_username_info_text_two': "You can use a-z, 0-9 and _. Minimum length - 5 characters",
          'about_you': "You can add a few lines about yourself. Anyone who opens a profile will see this text",
          'turn_on_GPS_service_from_your_phone': "Turn on GPS service from your phone",
          'delete_and_leave_the_group': "Delete and leave the group",
          'delete': "Delete",
          'do_you_want_to_leave_the_group': "Do you want to leave the group?",
          'add_members': "Add members",
          'members': "Members",
          'loading_file': "Loading file",
          'post_a_group_photo': "Post a group photo",
          'do_you_want_to_delete_the_group': "Do you want to delete the group?",
          'admins': "Admins",
          'personal': "Personal",
          'public': "Public",
          'group_name': "Group name",
          'assign_a_new_image': "Assign a new image",
          'group_type': "Group type",
          'editing': "Editing",
          'what_news_do_you_have': "What news do you have?",
          'create_a_post': "Create a post",
          'visited_your_profile': "visited your profile",
          'liked_the_post_you_posted': "liked the post you posted",
          'commented_on_the_post_you_posted': "commented on the post you posted",
          'responded_to_your_comment_in_the_post': "responded to your comment in the post",
          'are_you_sure_you_want_to_blacklist_this_user': "Are you sure you want to blacklist this user?",
          'Privacy_and_Security': "Privacy and Security",
          'Account': "Account",
          'Blocked_users': "Blocked users",
          'Safety': "Safety",
          'count_blocked_users': "blocked users",
          'unblok_a_user': "Unblock a user",
          'There_are_no_blocked_users': "There are no blocked users",
          'Chats_are_not_available': "Chats are not available",
          'Devices': "Devices",
          'Confidentiality': "Confidentiality",
          'Start_a_new_chat': "Start a new chat",
          'Turn_on_the_GPS_service_from_your_phone': "Turn on the GPS service from your phone",
          'show_phone_all': "All",
          'show_phone_not_all': "Nobody",
          'Who_can_see_my_phone_number': "Who can see my phone number?",
          'Private_group': "Private group",
          'Mass_group_text': "Public groups are searchable and anyone can join",
          'phone_number_all_text': "Visitors to your profile can see your phone number",
          'phone_number_not_all_text': "No one can see your phone number",
        },
      };
}
